version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_db
    environment:
      - POSTGRESQL_USERNAME=spring
      - POSTGRESQL_PASSWORD=boot
      - POSTGRESQL_DATABASE=hyperloop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ default messaging port
      - "15672:15672" # RabbitMQ Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  app-network:
    driver: bridge